#!/bin/csh -f 
#################################################################
###                                                           ###
### This script is proprietary and confidential information   ###
### of Novas Software Inc.  and may be used and disclosed     ###
### only as authorized in a license agreement controlling     ###
### such use and disclosure.                                  ###
###                                                           ###
###                 Author : Nathan Hsiung                    ###
###                  Date   : 02/18/2005                      ###
###                                                           ###
###         Copyright(C) Novas Software Inc. 2006             ###
###                    ALL RIGHTS RESERVED                    ###
###                                                           ###
#################################################################

################################################
#  step1 setup environment
################################################
# Uncomment to run in Novas environment.
#setenv NOVAS_HOME   /novas/tools/Novas/verdi/latest
#setenv VCS_HOME     /novas/tools/Synopsys/VCS/vcs_vY-2006.06-SP1-18

switch(`uname`)
    case SunOS*:
        set novas_platform=SOL2
        set sn_platform=solaris
    breaksw
    case Linux*:
        set novas_platform=LINUX
        set sn_platform=linux
    breaksw
endsw
################################################
#  step2 process cmdline opts
################################################
# --test: File name containing a test program block; default='../sv/test_random.sv'

set test=../sv/test_random.sv
while ($#argv > 0)
    switch($argv[1])
        case --test:
            shift
            if ($#argv > 0) then
                if (!(-e $argv[1])) then
                    echo "Error: Test program '$argv[1]': File not found"
                    exit 1
                endif
                set test=$argv[1]
            else
                echo "Error: --test: No test file name given"
                exit 1
            endif
        breaksw
        default
            echo "Error: '$argv[1]': Unrecognized switch"
            exit 1
        breaksw
    endsw
    shift
end
echo "Debug: test=$test"

setenv VERDI_SVTB_BETA 1
setenv VERDI_SVTB_MACRO 1
setenv VERDI_SVTB_DEBUG 1
setenv SIGNAL_BASED_BA 1
setenv EXPAND_MACRO_DEBUG 1
setenv VERDI_SVTB_CONSTRAINT 1



# To run in Novas environment, use the full path to Verdi below.
#$NOVAS_HOME/bin/verdi
cp novas_svtb.fsdb novas.fsdb 
cp novas.rc.bak novas.rc
#verdi -macrodebug -nologo -sv display.svh -f run_sv.f -ssf novas.fsdb +define+SVA_ENABLE +incdir+../sv -ntb_opts vmm $test
verdi -macrodebug -nologo -sv display.svh -f run_sv.f -ssf novas.fsdb +define+SVA_ENABLE +incdir+../sv -ntb_opts vmm $test -tbbr_debug -simType ModelSim -simBin vsim -simOpt system 
