//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 7? 12 2020 21:25:20
//
//      Input file      : 
//      Component name  : gmii_to_rgmii_0_resets
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module gmii_to_rgmii_0_resets(reset, ref_clk, idelayctrl_reset);
   input     reset;
   input     ref_clk;
   output    idelayctrl_reset;
   reg       idelayctrl_reset;
   
   
   wire      idelayctrl_reset_sync;
   reg [3:0] idelay_reset_cnt;
   
   
   gmii_to_rgmii_0_reset_sync_ex idelayctrl_reset_gen(.clk(ref_clk), .reset_in(reset), .reset_out(idelayctrl_reset_sync));
   
   
   always @(posedge ref_clk)
      
      begin
         if (idelayctrl_reset_sync == 1'b1)
         begin
            idelay_reset_cnt <= {4{1'b0}};
            idelayctrl_reset <= 1'b1;
         end
         else
         begin
            idelayctrl_reset <= 1'b1;
            case (idelay_reset_cnt)
               4'b0000 :
                  idelay_reset_cnt <= 4'b0001;
               4'b0001 :
                  idelay_reset_cnt <= 4'b0010;
               4'b0010 :
                  idelay_reset_cnt <= 4'b0011;
               4'b0011 :
                  idelay_reset_cnt <= 4'b0100;
               4'b0100 :
                  idelay_reset_cnt <= 4'b0101;
               4'b0101 :
                  idelay_reset_cnt <= 4'b0110;
               4'b0110 :
                  idelay_reset_cnt <= 4'b0111;
               4'b0111 :
                  idelay_reset_cnt <= 4'b1000;
               4'b1000 :
                  idelay_reset_cnt <= 4'b1001;
               4'b1001 :
                  idelay_reset_cnt <= 4'b1010;
               4'b1010 :
                  idelay_reset_cnt <= 4'b1011;
               4'b1011 :
                  idelay_reset_cnt <= 4'b1100;
               4'b1100 :
                  idelay_reset_cnt <= 4'b1101;
               4'b1101 :
                  idelay_reset_cnt <= 4'b1110;
               default :
                  begin
                     idelay_reset_cnt <= 4'b1110;
                     idelayctrl_reset <= 1'b0;
                  end
            endcase
         end
      end
   
endmodule
