//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 7? 12 2020 21:25:08
//
//      Input file      : 
//      Component name  : gmii_to_rgmii_0_clocking
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module gmii_to_rgmii_0_clocking(clkin, clkin_out, reset, mmcm_locked, gmii_clk_125m, gmii_clk_25m, gmii_clk_2_5m);
   input   clkin;
   output  clkin_out;
   input   reset;
   output  mmcm_locked;
   output  gmii_clk_125m;
   output  gmii_clk_25m;
   output  gmii_clk_2_5m;
   
   
   wire    clkin_bufg;
   
   wire    clkfbout;
   wire    clkfbout_buf;
   wire    clk_125m_i;
   wire    clk_25m_i;
   wire    clk_10;
   wire    clk_2_5m_i;
   
   
   BUFG i_bufg_clk_in(.i(clkin), .o(clkin_bufg));
   
   
   MMCME2_ADV #("OPTIMIZED", 1'b0, "ZHOLD", 1'b0, 1, 5.000, 0.000, 1'b0, 8.000, 0.000, 0.500, 1'b0, 40, 0.000, 0.500, 1'b0, 100, 0.000, 0.500, 1'b0, 5.000, 0.010) mmcm_adv_inst(.clkfbout(clkfbout), .clkfboutb(), .clkout0(clk_125m_i), .clkout0b(), .clkout1(clk_25m_i), .clkout1b(), .clkout2(clk_10), .clkout2b(), .clkout3(), .clkout3b(), .clkout4(), .clkout5(), .clkout6(), .clkfbin(clkfbout), .clkin1(clkin_bufg), .clkin2(1'b0), .clkinsel(1'b1), .daddr(1'b0), .dclk(1'b0), .den(1'b0), .di(1'b0), .do(), .drdy(), .dwe(1'b0), .psclk(1'b0), .psen(1'b0), .psincdec(1'b0), .psdone(), .locked(mmcm_locked), .clkinstopped(), .clkfbstopped(), .pwrdwn(1'b0), .rst(reset));
   
   
   BUFR #("4") clk10_div_buf(.i(clk_10), .ce(1'b1), .clr(1'b0), .o(clk_2_5m_i));
   
   assign clkin_out = clkin_bufg;
   
   assign gmii_clk_125m = clk_125m_i;
   assign gmii_clk_25m = clk_25m_i;
   assign gmii_clk_2_5m = clk_2_5m_i;
   
endmodule
