
   `undef APB_DATA_WIDTH
   `undef APB_DW_EQ_32
   `undef TIM_NEWMODE_VAL
   `undef NUM_TIMERS
   `undef NUM_TIMERS_GTE_1
   `undef NUM_TIMERS_GTE_2
   `undef TIM_INTRPT_PLRITY
   `undef TIM_INTR_IO
   `undef TIMER_WIDTH_1
   `undef TIMER_HAS_TOGGLE_1
   `undef TIM_METASTABLE_1
   `undef TIM_PULSE_EXTD_1
   `undef TIM_COHERENCY_1
   `undef TIMER_WIDTH_2
   `undef TIMER_HAS_TOGGLE_2
   `undef TIM_METASTABLE_2
   `undef TIM_PULSE_EXTD_2
   `undef TIM_COHERENCY_2
   `undef TIMER_WIDTH_3
   `undef TIMER_HAS_TOGGLE_3
   `undef TIM_METASTABLE_3
   `undef TIM_PULSE_EXTD_3
   `undef TIM_COHERENCY_3
   `undef TIMER_WIDTH_4
   `undef TIMER_HAS_TOGGLE_4
   `undef TIM_METASTABLE_4
   `undef TIM_PULSE_EXTD_4
   `undef TIM_COHERENCY_4
   `undef TIMER_WIDTH_5
   `undef TIMER_HAS_TOGGLE_5
   `undef TIM_METASTABLE_5
   `undef TIM_PULSE_EXTD_5
   `undef TIM_COHERENCY_5
   `undef TIMER_WIDTH_6
   `undef TIMER_HAS_TOGGLE_6
   `undef TIM_METASTABLE_6
   `undef TIM_PULSE_EXTD_6
   `undef TIM_COHERENCY_6
   `undef TIMER_WIDTH_7
   `undef TIMER_HAS_TOGGLE_7
   `undef TIM_METASTABLE_7
   `undef TIM_PULSE_EXTD_7
   `undef TIM_COHERENCY_7
   `undef TIMER_WIDTH_8
   `undef TIMER_HAS_TOGGLE_8
   `undef TIM_METASTABLE_8
   `undef TIM_PULSE_EXTD_8
   `undef TIM_COHERENCY_8
   `undef TIM_ADDR_SLICE_RHS
   `undef TIM_ADDR_SLICE_LHS
   `undef TIM_WDATA_WIDTH
   `undef TIM_RDATA_WIDTH
   `undef MAX_APB_DATA_WIDTH
   `undef TIM_CTL_WIDTH
   `undef TIM_MAX_TIMER_WIDTH
   `undef TIM_MAX_TIMERS_WIDTH
   `undef TIM_FREE_RUNNING
   `undef TIM_USER_DEFINED
   `undef TIM_MAX_TIMERS
   `undef MAX_CURRVALUE_WIDTH
   `undef TIM1_CV_INDEX
   `undef TIM2_CV_INDEX
   `undef TIM3_CV_INDEX
   `undef TIM4_CV_INDEX
   `undef TIM5_CV_INDEX
   `undef TIM6_CV_INDEX
   `undef TIM7_CV_INDEX
   `undef TIM8_CV_INDEX
   `undef TIM_INDIVIDUAL
   `undef TIM_COMBINED
   `undef TIM_VERSION_ID
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM06
   `undef RM_BCM07
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM22
   `undef RM_BCM23
   `undef RM_BCM24
   `undef RM_BCM25
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM35
   `undef RM_BCM43
   `undef RM_BCM44
   `undef RM_BCM46_A
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM47
   `undef RM_BCM48
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM60
   `undef RM_BCM62
   `undef RM_BCM64
   `undef RM_BCM65
   `undef RM_BCM66
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM76
   `undef TIMER1LC_OFFSET
   `undef TIMER1CV_OFFSET
   `undef TIMER1CR_OFFSET
   `undef TIMER1EOI_OFFSET
   `undef TIMER1INTST_OFFSET
   `undef TIMER2LC_OFFSET
   `undef TIMER2CV_OFFSET
   `undef TIMER2CR_OFFSET
   `undef TIMER2EOI_OFFSET
   `undef TIMER2INTST_OFFSET
   `undef TIMER3LC_OFFSET
   `undef TIMER3CV_OFFSET
   `undef TIMER3CR_OFFSET
   `undef TIMER3EOI_OFFSET
   `undef TIMER3INTST_OFFSET
   `undef TIMER4LC_OFFSET
   `undef TIMER4CV_OFFSET
   `undef TIMER4CR_OFFSET
   `undef TIMER4EOI_OFFSET
   `undef TIMER4INTST_OFFSET
   `undef TIMER5LC_OFFSET
   `undef TIMER5CV_OFFSET
   `undef TIMER5CR_OFFSET
   `undef TIMER5EOI_OFFSET
   `undef TIMER5INTST_OFFSET
   `undef TIMER6LC_OFFSET
   `undef TIMER6CV_OFFSET
   `undef TIMER6CR_OFFSET
   `undef TIMER6EOI_OFFSET
   `undef TIMER6INTST_OFFSET
   `undef TIMER7LC_OFFSET
   `undef TIMER7CV_OFFSET
   `undef TIMER7CR_OFFSET
   `undef TIMER7EOI_OFFSET
   `undef TIMER7INTST_OFFSET
   `undef TIMER8LC_OFFSET
   `undef TIMER8CV_OFFSET
   `undef TIMER8CR_OFFSET
   `undef TIMER8EOI_OFFSET
   `undef TIMER8INTST_OFFSET
   `undef TIMERSINTST_OFFSET
   `undef TIMERSEOI_OFFSET
   `undef TIMERSRAW_OFFSET
   `undef TIM_VID_OFFSET
   `undef TIMER1LC2_OFFSET
   `undef TIMER2LC2_OFFSET
   `undef TIMER3LC2_OFFSET
   `undef TIMER4LC2_OFFSET
   `undef TIMER5LC2_OFFSET
   `undef TIMER6LC2_OFFSET
   `undef TIMER7LC2_OFFSET
   `undef TIMER8LC2_OFFSET

