# ------------------------------------------------------------------
# Clean
# ------------------------------------------------------------------

clean :
	rm -f dynamic_simulation/assert_vlog95/*/log/*.BAK
	rm -f dynamic_simulation/assert_sva05/*/log/*.BAK
	rm -f dynamic_simulation/ovl_vlog95/*/log/*.BAK
	rm -f dynamic_simulation/ovl_sva05/*/log/*.BAK
	rm -f *~ */*~ */*/*~ */*/*/*~ */*/*/*/*~
